# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
   main.show-banner: false
   
   datasource:
      url: jdbc:postgresql://minishop-db:5432/postgres
      driverClassName: org.postgresql.Driver
      username: postgres
      password: password
      
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
      hibernate:
         naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
         
      properties:
         hibernate:
            format_sql: true
            globally_quoted_identifiers: true
      
   liquibase:
      change-log: classpath:db/changelog/liquibase-changeLog.xml
      
      